Docsify implementation
realdecoy/rdvue pull request #111
Opened 2020-12-11 22:04 UTC by apeart-rd

Implemented Docsify and transferred all existing confluence documentation under Docs (draft).

2020-12-14 19:39 UTC, taslangraham requested changes
- Some navigations do not work because of incorrect casing on files referenced inside _sidebar.md
- We need a README.md file that loads when we are at '/' 
- Adding a cover/landing page would be cool - https://docsify.js.org/#/cover

2020-12-15 17:10 UTC, OrandiH commented
- Not sure where this is coming from on the main screen - https://share.getcloudapp.com/bLu0qL6Z
- I do think we need a theme.
- Same comment as Taslan re navigations.

2020-12-16 16:29 UTC, taslangraham requested changes
Please see comments made throughout.

Not sure why, but only sub-sections has highlighted navigations. See images:
1)https://share.getcloudapp.com/p9urNy2r - sub-section
2)https://share.getcloudapp.com/rRu0WKxv - a main section. Navigating to it doe not give the blue highlight like in the previous picture

2020-12-16 16:29 UTC, taslangraham commented on docs/GettingStarted.md
>  The project will be served at [http://localhost:8080/](http://localhost:8080/) by default. This information will also be printed out in your terminal. Visiting the link the app is served on will disp
The entire getting started documentation is replaced here. Is this intentional?

2020-12-16 16:29 UTC, taslangraham commented on docs/index.html
>        homepage: 'gettingStarted.md',
The getting started document has incorrect info in it.  Update it with the contents on confluence

2020-12-16 16:29 UTC, taslangraham commented on docs/index.html
> +      repo: 'https://github.com/realdecoy/rdvue/',
Hey, could we add a cover page as well? https://docsify.js.org/#/cover

2020-12-17 05:08 UTC, OrandiH commented on docs/_sidebar.md
> +  - [**Getting Started**](/)
I noticed there was a issue with the layout for the items for CLI Commands, please see link here -> https://share.getcloudapp.com/2Nu0vwA8

2020-12-17 05:08 UTC, OrandiH requested changes
Please see comments.

2020-12-22 18:59 UTC, OrandiH approved these changes

2021-01-08 18:26 UTC, taslangraham approved these changes

2021-01-11 21:14 UTC, merged