FP-322/Implement New Preset Configs
realdecoy/rdvue pull request #82
Opened 2020-11-03 19:50 UTC by Kevoniatom

2020-11-04 21:09 UTC, OrandiH commented on template/template.json
> +      "descrition": "Vuetify, Localization, FontAwesome, PWA"
*description

2020-11-04 21:10 UTC, OrandiH commented on template/template.json
> +      "descrition": "Buefy, Localization, FontAwesome, PWA"
*description

2020-11-04 21:10 UTC, OrandiH requested changes
@Kevoniatom see comments.

2020-11-04 21:43 UTC, Kevoniatom commented
updated

2020-11-04 21:43 UTC, Kevoniatom commented
@OrandiH

2020-11-05 14:39 UTC, OrandiH approved these changes
@Kevoniatom approved and ready for merge.

2020-11-09 20:35 UTC, OrandiH requested changes
Changes needed.

2020-11-09 20:57 UTC, OrandiH approved these changes

2020-11-09 20:58 UTC, merged